
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hiberate:
        format_sql: true
  application:
    name: user-service
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: group1
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
logging:
  level:
    org.springframework.security: TRACE
