spring:
  application:
    name: movie-service
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: demoProject
      uri: mongodb://localhost:27017/demoProject
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hiberate:
        format_sql: true

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false
logging:
  level:
    org.springframework.security: TRACE
